# config/services.yaml
services:
  FaustDDD\Symfony1cImport\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Domain/'
      - '../src/Infrastructure/Controller/'

  FaustDDD\Symfony1cImport\Application\Service\Cml1cInteractor:
    autowire: true
    arguments:
      $projectDir: '%kernel.project_dir%'
      $login: '%faustddd_1c_import.login%'
      $password: '%faustddd_1c_import.password%'

  FaustDDD\Symfony1cImport\Infrastructure\Controller\Import1CController:
    public: true
    autowire: true
    tags: [controller.service_arguments]